Domain Sockets and Named Pipes
fiskaltrust/middleware-launcher pull request #151
Opened 2024-01-03 10:19 UTC by pawelvds

2024-01-03 20:40 UTC, pawelvds commented on src/fiskaltrust.Launcher/Commands/HostCommand.cs
> +            AddOption(new Option<string?>("--named-pipe-name"));
You're right. I wasn't sure and I expected it so I am going to delete it, thanks Paul

2024-01-03 20:54 UTC, pawelvds commented on src/fiskaltrust.Launcher/Commands/HostCommand.cs
> -                        opts.BackgroundServiceExceptionBehavior = BackgroundServiceExceptionBehavior.StopHost;
aye,no harm done, but it's obvious, so I'm removing it

2024-01-03 21:01 UTC, pawelvds commented on src/fiskaltrust.Launcher/Commands/HostCommand.cs
> -                        opts.BackgroundServiceExceptionBehavior = BackgroundServiceExceptionBehavior.StopHost;
yes yes BackgroundServiceExceptionBehavior is already set to StopHost by default, so no need to set it here :)

2024-01-03 21:46 UTC, pawelvds commented on src/fiskaltrust.Launcher/Commands/HostCommand.cs
> -                        opts.BackgroundServiceExceptionBehavior = BackgroundServiceExceptionBehavior.StopHost;
https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.hosting.hostoptions.backgroundserviceexceptionbehavior?view=dotnet-plat-ext-8.0#microsoft-extensions-hosting-hostoptions-backgroundserviceexceptionbehavior

2024-01-04 12:46 UTC, volllly commented on src/fiskaltrust.Launcher/Commands/HostCommand.cs
> -                        opts.BackgroundServiceExceptionBehavior = BackgroundServiceExceptionBehavior.StopHost;
🙏

2024-01-11 09:26 UTC, volllly requested changes

2024-01-11 09:26 UTC, volllly commented on src/fiskaltrust.Launcher.Common/Configuration/Configuration.cs
> +        public string? LauncherServiceUri { get => _launcherServiceUri; set => _launcherServiceUri = value; }
```suggestion
        private string? _launcherServiceUri;
        [JsonPropertyName("launcherServiceUri")]
        public string? LauncherServiceUri {
            get => WithDefault(
                _launcherServiceUri,
                OperatingSystem.IsWindows()
                    ? $"net.pipe://localhost/fiskaltrust-{_cashboxId}" 
                    : $"/tmp/fiskaltrust-{_cashboxId}.sock"
            );
            set => _launcherServiceUri = value;
        }
```

2024-01-11 09:26 UTC, volllly commented on src/fiskaltrust.Launcher.Common/Configuration/Configuration.cs
> +        }
We have a defaults mechanism already that we should reuse

2024-01-11 09:26 UTC, volllly commented on src/fiskaltrust.Launcher.Common/Configuration/Configuration.cs
```suggestion
```

2024-01-11 09:26 UTC, volllly commented on src/fiskaltrust.Launcher.Common/Configuration/Configuration.cs
> +        }
```suggestion
```

2024-01-11 09:26 UTC, volllly commented on src/fiskaltrust.Launcher/Commands/HostCommand.cs
> +                bool useDomainSockets)
```suggestion
            public HostOptions(string launcherConfiguration, string plebeianConfiguration, bool noProcessHostService, bool debugging)
```

2024-01-11 09:26 UTC, volllly commented on src/fiskaltrust.Launcher/Services/HostingService.cs
> +            {
The hosting service is only used to host the urls for `Queues` `SCU`s and Helpers.

We don't want to change anything in the hosting for them so we don't need to touch the hosting service.
```suggestion
```

2024-01-11 09:26 UTC, volllly commented on src/fiskaltrust.Launcher/Services/HostingService.cs
> +
```suggestion
```

2024-01-11 09:26 UTC, volllly commented on test/fiskaltrust.Launcher.UnitTest/Configuration/Configuration.cs
> +                deserialized.Should().BeEquivalentTo(configuration, options => options.Excluding(cfg => cfg.LauncherServiceUri));
```suggestion
                deserialized.Raw(d => configuration.Raw(c => d.Should().BeEquivalentTo(c, "")));

                deserialized.Should().BeEquivalentTo(deserialized);
```

2024-01-11 09:26 UTC, volllly commented on src/fiskaltrust.Launcher/ProcessHost/ProcessHostMonarcStartup.cs
> +        private void ConfigureKestrel(Uri launcherServiceUri, WebApplicationBuilder builder)
```suggestion
        private void ConfigureKestrelForIPC(Uri launcherServiceUri, WebApplicationBuilder builder)
```

2024-01-11 09:26 UTC, volllly commented on src/fiskaltrust.Launcher/ProcessHost/ProcessHostMonarcStartup.cs
> +            if (string.IsNullOrEmpty(_launcherConfiguration.LauncherServiceUri))
You can remove the whole code in this if. It's functionality was to check if kestrel is ready so we can overwrite the launcher port with the actual port if it was `0` (using dynamic binding). As we don't have that anymore just remove it.

2024-01-11 09:26 UTC, volllly commented on src/fiskaltrust.Launcher/ProcessHost/ProcessHostMonarcStartup.cs
>          private readonly TaskCompletionSource<Uri> _kestrelReady;
We can remove the `_kestrelReady` property.

2024-01-11 09:26 UTC, volllly commented on src/fiskaltrust.Launcher/ProcessHost/ProcessHostMonarcStartup.cs
> +        private readonly WebApplicationBuilder _webHostBuilder;
```suggestion
```

The ProcessHost service should not be started here.

2024-01-11 09:26 UTC, volllly commented on src/fiskaltrust.Launcher/Commands/RunCommand.cs
> +            builder.WebHost.ConfigureBinding(new Uri($"http://[::1]:{commonProperties.LauncherConfiguration.LauncherServiceUri}"), protocols: HttpProtocols.Http2);
The ProcessHostService server is started here.
We need to use the functionality you provided in the `ConfigureKestrel` method instead of this line.

2024-01-11 09:26 UTC, volllly commented on src/fiskaltrust.Launcher/Commands/HostCommand.cs
We don't use grpc over http anymore. You'll need to create a GrpcChannel like described

here https://learn.microsoft.com/en-us/aspnet/core/grpc/interprocess-namedpipes?view=aspnetcore-8.0#client-configuration on windows.

and here https://learn.microsoft.com/en-us/aspnet/core/grpc/interprocess-uds?view=aspnetcore-8.0#client-configuration on linux.

2024-01-22 14:01 UTC, volllly approved these changes

2024-01-22 14:01 UTC, merged